### PR TITLE
Alfa section name change

### LINKED ISSUE #31: Change the section  naming conventions in the ALFA report
**Is your feature request related to a problem? Please describe.**
I would like the title of the sections of the alfa in the multiqc report to be more meaningful. 

**Describe the solution you'd like**
Replace some specific ALFA names with more descriptive ones. In particular the UniqueMultiple with MultimappersIncluded as the UniqueMultiple is confusing and the Unique with UniqueMappers.

### PR DESCRIPTION
**Pull request by mkatsanto**
## Description

Replace some specific ALFA names with more descriptive ones. In particular the UniqueMultiple with MultimappersIncluded as the UniqueMultiple is confusing and the Unique with UniqueMappers.

Fixes #31  

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I have not reduced the existing code coverage

### CODE REVIEW

**Comment by fgypas** [comment]
I tested locally and the report looks good to me 
Screen Shot 2021-08-23 at 19 49 53

**Comment by AngryMaciek** [comment]
1. I cannot merge the changes in their current form; please see the discussion here: https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/164
2. Expected output report should also be updated (i.e. run `multiqc` with this plugin on the data under `tests/ALFA` and update the _HTML_ file there).

**Comment by fgypas** [comment]
Hi @AngryMaciek 
Where would one put the flag? Do we have some argparse or some optparse available in the current repo? Or should we change the original multiqc code?

**Comment by AngryMaciek** [comment]
@fgypas 

I just tested out `multiqc` and it does not seem like you can provide your own flags.  
We would indeed need to fork the whole tool and introduce our modification into the original codebase. But that would be a wrong approach too since we would like to develop these plugins properly for the whole community and **not** enforce all users to use our "special" fork of _MutliQC_.  
Therefore my proposition with a `--flag` would not work.  
What we theoretically could do is to introduce a global variable at the beginning of [this file](https://github.com/zavolanlab/multiqc-plugins/blob/dev/modules/ALFA/ALFA.py), conditionalise on it and tell the users that they can adjust it and re-install the plugins. But that is not a clean solution either and I personally do not like it (would require re-building containers too).

**Pull request closed without merging**
